name: Build and Deploy to GCP

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish -c Release -o publish

    - name: Authenticate GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build Docker
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hospital-repo/hospital-app:latest .

    - name: Push Docker
      run: |
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hospital-repo/hospital-app:latest

    - name: Deploy Cloud Run
      run: |
        gcloud run deploy hospital-app \
        --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hospital-repo/hospital-app:latest \
        --region us-central1 \
        --platform managed \
        --allow-unauthenticated \
        --port 8080 \
        --timeout 300